export type AppColorType =
  | 'white'
  | 'brightBlue'
  | 'daySkyBlue'
  | 'treeGreen'
  | 'blackEel'
  | 'dirtyOrange'
  | 'scarletRed'
  | 'alabaster'
  | 'whiteSmoke'
  | 'davyGrey'
  | 'lightGrey'
  | 'paleSky'
  | 'moonMist'
  | 'titanWhite';
